[package]
authors = ["Bogdan Arabadzhi <bogdan.today@gmail.com>"]
name = "binpatch"
version = "0.1.0"

[dependencies]
data-encoding = "2.0.0-rc.2"
clippy = {version = "*", optional = true}

[features]
default = []
